version: 0.0
os: linux
files:
  - source: /
    destination: /opt/registration/registration-api

permissions:
  - object: /opt/registration/registration-api
    owner: ec2-user

hooks:
  ApplicationStop:
    - location: deploy_scripts/stop.sh

  ApplicationStart:
    - location: deploy_scripts/start.sh

  BeforeInstall:
    - location: deploy_scripts/purge.sh
