version: '2'

services:
  nginx:
    image: nginx:stable
    environment:
      API_SERVER_NAME: localhost
      API_SSL_CERTIFICATE: /ssl/localhost.cert
      API_SSL_CERTIFICATE_KEY: /ssl/localhost.key
    links:
      - kansa
    ports:
      - "4430:443"
    volumes:
      - ./nginx/conf.template:/nginx.conf.template:ro
      - ./nginx/ssl:/ssl:ro
      - ./kansa/admin/dist:/usr/share/nginx/html/kansa/admin:ro
    command: /bin/bash -c "envsubst '$$API_SERVER_NAME $$API_SSL_CERTIFICATE $$API_SSL_CERTIFICATE_KEY' < /nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  kansa:
    build: ./kansa/server
    env_file: ./kansa/server/dev.env
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - postgres
    ports:
      - "3000:3000"
    restart: always

  postgres:
    image: postgres:9.5
    env_file: ./postgres/dev.env
    expose:
      - "5432"
    restart: always
    volumes:
      - pgdata:/pgdata
      - ./postgres/damm:/damm:ro
      - ./postgres/init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:
