app:
  build: .
  links:
    - postgres

proxy:
  image: jwilder/nginx-proxy:latest
  env_file: .env
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./fixtures/ssl/certs:/etc/nginx/certs
  restart: always
  links:
   - app

postgres:
  image: postgres:9.4
  env_file: .env
  restart: always
