version: '2'

# For full config, see also docker-compose.{override,prod}.yml

volumes:
  pgdata:

services:
  nginx:
    build: ./nginx
    links:
      - hugo
      - members
      - art
    entrypoint: /bin/bash -c "envsubst '$$SERVER_NAME $$SSL_CERTIFICATE $$SSL_CERTIFICATE_KEY' < /nginx.conf.template > /usr/local/openresty/nginx/conf/nginx.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"

  hugo:
    build: ./hugo
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - postgres
    expose:
      - "3000"

  members:
    build: ./members
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - kyyhky
      - postgres
      - tuohi
    expose:
      - "3000"

  art:
    build: ./art
    entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
    links:
      - postgres
    expose:
      - "3000"

  tuohi:
    image: eeemeli/pdf-form-fill:0.2
    expose:
      - "3000"
    environment:
      PDF_TEMPLATE_DIR: /templates
    volumes:
      - ./tuohi/templates:/templates:ro

  kyyhky:
    build: ./kyyhky
    entrypoint: ./wait-for-it.sh redis:6379 -- npm start
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    expose:
      - "3000"

  redis:
    image: redis:3.2
    expose:
      - "6379"

  postgres:
    image: postgres:9.5
    environment:
      PGDATA: /pgdata
      PGUSER: admin
      POSTGRES_DB: api
      POSTGRES_USER: admin
    expose:
      - "5432"
    volumes:
      - pgdata:/pgdata
      - ./postgres/init/10-admin-init.sql:/docker-entrypoint-initdb.d/10-admin-init.sql:ro
      - ./postgres/init/19-install-damm.sql:/docker-entrypoint-initdb.d/19-install-damm.sql:ro
      - ./postgres/init/20-kansa-init.sql:/docker-entrypoint-initdb.d/20-kansa-init.sql:ro
      - ./postgres/init/25-day-passes.sql:/docker-entrypoint-initdb.d/25-day-passes.sql:ro
      - ./postgres/init/25-payments.sql:/docker-entrypoint-initdb.d/25-payments.sql:ro
      - ./postgres/init/25-public-data.sql:/docker-entrypoint-initdb.d/25-public-data.sql:ro
      - ./postgres/init/30-hugo-init.sql:/docker-entrypoint-initdb.d/30-hugo-init.sql:ro
      - ./postgres/init/40-raami-init.sql:/docker-entrypoint-initdb.d/40-raami-init.sql:ro
