version: '2'

# included by default along with docker-compose.yml

services:
  nginx:
    environment:
      API_SERVER_NAME: localhost
      API_SSL_CERTIFICATE: /ssl/localhost.cert
      API_SSL_CERTIFICATE_KEY: /ssl/localhost.key
    ports:
      - "4430:443"
    volumes:
      - ./nginx/ssl:/ssl:ro

  hugo:
    env_file: ./hugo/server/dev.env

  kansa:
    environment:
      API_ROOT: https://localhost:4430
      CORS_ORIGIN: http://localhost:8080
      DATABASE_URL: postgres://kansa:pwd@postgres:5432/api
      SESSION_SECRET: dev secret
      SENDGRID_APIKEY:

  kyyhky:
    env_file: ./kyyhky/dev.env

  postgres:
    environment:
      POSTGRES_PASSWORD: adminpwd
      KANSA_PG_PASSWORD: pwd
      HUGO_PG_PASSWORD: pwd
