version: '2'

# For full config, see also docker-compose.{override,prod}.yml
services:
  nginx:
    build: ./nginx
    links:
      - hugo
      - members
      - art
    entrypoint: /bin/bash -c "envsubst '$$SERVER_NAME $$SSL_CERTIFICATE $$SSL_CERTIFICATE_KEY' < /nginx.conf.template > /usr/local/openresty/nginx/conf/nginx.conf && /usr/local/openresty/bin/openresty -g 'daemon off;'"

  hugo:
    build: ./hugo
    entrypoint: npm start
    links: []
    expose:
      - "3000"

  members:
    build: ./members
    entrypoint: npm start
    links:
      - kyyhky
      - tuohi
    expose:
      - "3000"

  art:
    build: ./art
    entrypoint: npm start
    links: []
    expose:
      - "3000"

  tuohi:
    image: eeemeli/pdf-form-fill:0.2
    expose:
      - "3000"
    environment:
      PDF_TEMPLATE_DIR: /templates
    volumes:
      - ./tuohi/templates:/templates:ro

  kyyhky:
    build: ./kyyhky
    entrypoint: ./wait-for-it.sh redis:6379 -- npm start
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    links:
      - redis
    expose:
      - "3000"

  redis:
    image: redis:3.2
    expose:
      - "6379"
