app:
  build: app/
  env_file: .env
  links:
    - postgres

proxy:
  build: proxy/
  ports:
    - "80:80"
    - "443:443"
  links:
   - app
  volumes:
   - ../fixtures/ssl/certs:/etc/nginx/certs

postgres:
  image: postgres:9.4
  env_file: .env
  restart: always
