server:
  build: ./server
  env_file: ./server/dev.env
  entrypoint: ./wait-for-it.sh postgres:5432 -- npm start
  links:
    - postgres
  ports:
    - "3000:3000"

postgres:
  image: postgres:9.5
  env_file: ./server/dev.env
  expose:
    - "5432"
  restart: always
  volumes:
    - ./postgres/damm:/damm
    - ./postgres/init:/docker-entrypoint-initdb.d
